{% set python_min = "3.12" %}
{% set name = "statista" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/statista/archive/{{ version }}.tar.gz
  sha256: 78e65636e5b9e858268e7c4e82eab267a4742bc164c53aeb8fd6e8ed89ef7a57

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip >=22.3.1
  run:
    - python >={{ python_min }}
    - numpy >=2.0.1
    - matplotlib >=3.9.0
    - pandas >=2.1.0
    - scipy >=1.14.0
    - scikit-learn >=1.5.1
    - loguru >=0.7.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - statista

about:
  home: https://github.com/Serapieum-of-alex/statista
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: Statistical Package
  description: |
    Statistical Package.
  dev_url: https://github.com/Serapieum-of-alex/statista
  doc_url: https://serapieum-of-alex.github.io/statista/
  doc_source_url: https://github.com/Serapieum-of-alex/statista/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
