{% set name = "statista" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/statista/archive/{{ version }}.tar.gz
  sha256: 213c57ffa9712c3365ec2c8783ac67180134b3fdaaf8edbbd1ca610e403655ab

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python  >=3.7.1,<3.10
    - pip >=21.3.1
  run:
    - python >=3.7.1,<3.10
    - pip >=21.3.1
    - numpy >=1.21.2,<1.22.4
    - matplotlib-base >=3.4.2,<3.6.0
    - pandas >=1.3.2,<1.4.3
    - scipy >=1.8.1
    - scikit-learn >=0.24.2,<1.1.2
    - loguru >=0.5.3

test:
  imports:
    - statista

about:
  home: https://github.com/MAfarrag/statista
  license:  GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: Statistical Package
  description: |
    Statistical Package.
  dev_url: https://github.com/MAfarrag/statista
  doc_url: https://statista.readthedocs.io/
  doc_source_url: https://github.com/MAfarrag/statista/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
