{% set python_min = '3.12' %}
{% set name = "statista" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/statista/archive/{{ version }}.tar.gz
  sha256: d7e32f4e6b612bd0e67ed9ee5adcad783998f78cf5ba6ff36c7ea4436301694c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip >=22.3.1
  run:
    - python >={{ python_min }}
    - numpy >=2.0.1
    - pip >=23.2.1
    - matplotlib >=3.9.0
    - pandas >=2.1.0
    - scipy >=1.14.0
    - scikit-learn >=1.5.1
    - loguru >=0.7.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - statista

about:
  home: https://github.com/Serapieum-of-alex/statista
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: Statistical Package
  description: |
    Statistical Package.
  dev_url: https://github.com/Serapieum-of-alex/statista
  doc_url: https://statista.readthedocs.io/
  doc_source_url: https://github.com/MAfarrag/Serapieum-of-alex/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
