{% set name = "statista" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/statista/archive/{{ version }}.tar.gz
  sha256: 8cfbe06d329d4e953d6ec0859bdc1c9b246c962081dae43d513c9c857e97f35c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9,<3.15
    - pip >=22.3.1
    - poetry >=1.1.15
  run:
    - python >=3.9,<3.15
    - pip >=22.3.1
    - numpy ==1.23.5
    - matplotlib >=3.5.3
    - pandas >=1.4.4
    - scipy >=1.9.0
    - scikit-learn >=1.1.1
    - loguru >=0.6.0

test:
  imports:
    - statista

about:
  home: https://github.com/MAfarrag/statista
  license:  GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: Statistical Package
  description: |
    Statistical Package.
  dev_url: https://github.com/MAfarrag/statista
  doc_url: https://statista.readthedocs.io/
  doc_source_url: https://github.com/MAfarrag/statista/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
