{% set name = "statista" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/statista/archive/{{ version }}.tar.gz
  sha256: 8489f4b4195d94621e020b093b443a64061580f0982b8a840a6d5f49beca4484

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python  >=3.9,<3.12
    - pip >=22.2.2
  run:
    - python >=3.9,<3.12
    - pip >=21.2.2
    - numpy >=1.21.2,<1.22.4
    - matplotlib >=3.5.3
    - pandas >=1.4.4
    - scipy >=1.9.1
    - scikit-learn >=1.1.2
    - loguru >=0.6.0

test:
  imports:
    - statista

about:
  home: https://github.com/MAfarrag/statista
  license:  GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: Statistical Package
  description: |
    Statistical Package.
  dev_url: https://github.com/MAfarrag/statista
  doc_url: https://statista.readthedocs.io/
  doc_source_url: https://github.com/MAfarrag/statista/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
