{% set name = "statista" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/MAfarrag/statista/archive/{{ version }}.tar.gz
  sha256: 53af1a5b34d940bdac47971c75c05bd61dcd6c78cd58e23f4273d4b015ccf1ee

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python  >=3.9,<3.12
    - pip >=22.2.2
  run:
    - python >=3.9,<3.12
    - pip >=22.2.2
    - numpy >=1.21.2,<1.22.4
    - matplotlib >=3.5.3
    - pandas >=1.4.4
    - scipy >=1.9.1
    - scikit-learn >=1.1.1
    - loguru >=0.6.0

test:
  imports:
    - statista

about:
  home: https://github.com/MAfarrag/statista
  license:  GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.md
  summary: Statistical Package
  description: |
    Statistical Package.
  dev_url: https://github.com/MAfarrag/statista
  doc_url: https://statista.readthedocs.io/
  doc_source_url: https://github.com/MAfarrag/statista/main/README.md

extra:
  recipe-maintainers:
    - MAfarrag
